version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kantor
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Adjust this path to where your 'sql' directory is located on the host machine
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  frontend:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  backend:
    build:
      context: ./backend/src/backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql-db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: kantor
    depends_on:
      - mysql-db

volumes:
  mysql-data:
